# xorg
# if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
#   exec startx
# fi

# wayland
# If running from tty1 start sway
# [ "$(tty)" = "/dev/tty1" ] && exec dbus-run-session sway
#
# Huprland

[ "$(tty)" = "/dev/tty1" ] && exec dbus-run-session Hyprland



# if uwsm check may-start && uwsm select; then
# 	exec uwsm start default
# fi
